export { default as Initial } from "./initial";
export { default as Main } from "./main";
export { default as Home } from "./home";
export { default as Login } from "./login";
export { default as Forgot } from "./forgot";
export { default as Signup } from "./signup";
export { default as Otp } from "./otp";
export { default as CreateAccount } from "./createAccount";
export { default as Profile } from "./profile"
export { default as Sale } from "./sale"
export { default as Invoice } from "./invoice"
export { default as PrivacyPolicy } from "./privacypolicy"
export { default as Tearms } from "./tearms"
export { default as Brand } from "./brand"
export { default as Model } from "./model"
export { default as UpdatePass } from "./updatepass"
export { default as Return } from "./return"
export { default as YourDevice } from "./device"
export { default as DeviceDetails } from "./devicedetails"
export { default as UploadImage } from "./uploadimage"
export { default as Confirm } from "./confirmpage"
export { default as ReturnDetails } from "./returndetails"
export { default as SaleDetails } from "./saledetails"

